config/routes.rb
Rails.application.routes.draw do
  resources :articles
  resources :authors
  resources :events
  resources :event_days
  resources :authors 

  get 'home/index'

  get 'calendar' => 'calendar#index'

  get 'login' => 'session#index'
  post 'login' => 'session#login'
  get 'logout' => 'session#logout'

  get 'admin' => 'admin#index'
  
  root 'home#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/author.rb
class Author < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/event_day.rb
class EventDay < ActiveRecord::Base
end

app/models/testmodel.rb
class Testmodel < ActiveRecord::Base
end

app/models/user.rb
require 'bcrypt'
class User < ActiveRecord::Base
	def self.authenticate (username, password)
		admin = User.take
		username = admin.username && BCrypt::Password.new(admin.hashed_password).is_password?(password)
	end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_action :authorize
	
	def index
	end

	private
		def authorize
			unless session[:logged_in]
				redirect_to root_path
			end
		end
end

app/controllers/event_days_controller.rb
class EventDaysController < ApplicationController
  before_action :set_event_day, only: [:show, :edit, :update, :destroy]
  before_action :authorize

  # GET /event_days
  # GET /event_days.json
  def index
    @event_days = EventDay.all
  end

  # GET /event_days/1
  # GET /event_days/1.json
  def show
  end

  # GET /event_days/new
  def new
    @event_day = EventDay.new
  end

  # GET /event_days/1/edit
  def edit
    @event_day = EventDay.find(params[:id])
  end

  # POST /event_days
  # POST /event_days.json
  def create
    @event_day = EventDay.new(event_day_params)

    respond_to do |format|
      if @event_day.save
        format.html { redirect_to @event_day, notice: 'Event day was successfully created.' }
        format.json { render :show, status: :created, location: @event_day }
      else
        format.html { render :new }
        format.json { render json: @event_day.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_days/1
  # PATCH/PUT /event_days/1.json
  def update
    respond_to do |format|
      if @event_day.update(event_day_params)
        format.html { redirect_to @event_day, notice: 'Event day was successfully updated.' }
        format.json { render :show, status: :ok, location: @event_day }
      else
        format.html { render :edit }
        format.json { render json: @event_day.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_days/1
  # DELETE /event_days/1.json
  def destroy
    @event_day.destroy
    respond_to do |format|
      format.html { redirect_to event_days_url, notice: 'Event day was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_day
      @event_day = EventDay.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_day_params
      params.require(:event_day).permit(:date, :icon)
    end

    def authorize
      unless session[:logged_in]
      redirect_to root_path
      end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

    #Get latest stories, display them in the newblocks
  	@articles = Article.last(8)
    @articles.reverse!

    @authors = []
    @articles.each do |article|
      @authors.push Author.find_by(id: article.author_id)
    end

    @events = []
    curr_date = Date.today
    date_buffer = Date.new(curr_date.year, curr_date.month, curr_date.day)
    day = EventDay.find_by(date: date_buffer)

    (0...6).each do
      if !day.nil?
        day_buffer = Event.where(day_id: day.id)

        day_buffer.each do |event|
          buffer = {}
          buffer[:title] = event.title
          buffer[:time] = event.time
          buffer[:icon] = event.icon
          buffer[:day] = day.date
          @events.push buffer
        end
      end

      date_buffer = date_buffer+1
      day = EventDay.find_by(date: date_buffer);
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/comic_helper.rb
module ComicHelper
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/helpers/event_days_helper.rb
module EventDaysHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/podcast_helper.rb
module PodcastHelper
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/event_days/_form.html.erb
<%= form_for(@event_day) do |f| %>
  <% if @event_day.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event_day.errors.count, "error") %> prohibited this event_day from being saved:</h2>

      <ul>
      <% @event_day.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <p>
      <%= f.label :date %><br>
      <%= f.date_field :date, value: Date.today %>
    </p>
    <p>
      <%= f.label :icon_url, "Icon URL" %><br>
      <%= f.text_field :icon %>
    </p> 
    <%= f.submit %>
  </div>
<% end %>

app/views/event_days/edit.html.erb
<h1>Editing event_day</h1>

<%= render 'form' %>
<%= link_to 'Add Event', new_event_path(day_id: @event_day.id) %>|
<%= link_to 'Show', @event_day %> |
<%= link_to 'Back', event_days_path %>

app/views/event_days/index.html.erb
<h1>Listing Event Days</h1>
<%= link_to 'New Event Day', new_event_day_path %> | <%= link_to 'Back To Admin Panel', admin_path %><br><br>
<div class="divider"></div>
<% @event_days.each do |event_day| %>
  <div class="itemListing">
    <div class="identifier">
      <%= event_day.date.strftime("%B %d, %Y") %>
    </div>
    <div class="actionBlock">
      <%= link_to 'Show', event_day %>&nbsp;|&nbsp;
      <%= link_to 'Edit', edit_event_day_path(event_day) %>&nbsp;|&nbsp;
      <%= link_to 'Destroy', event_day, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
    <div style="clear:both;"></div>
  </div><br> 
<% end %>

app/views/event_days/new.html.erb
<h1>New event_day</h1>

<%= render 'form' %>

<%= link_to 'Back', event_days_path %>

app/views/event_days/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_event_day_path(@event_day) %> |
<%= link_to 'Back', event_days_path %>