config/routes.rb
Rails.application.routes.draw do
  resources :articles
  resources :authors
  resources :events
  resources :event_days
  resources :authors 

  get 'home/index'

  get 'calendar' => 'calendar#index'

  get 'login' => 'session#index'
  post 'login' => 'session#login'
  get 'logout' => 'session#logout'

  get 'admin' => 'admin#index'
  
  root 'home#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/author.rb
class Author < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/event_day.rb
class EventDay < ActiveRecord::Base
end

app/models/testmodel.rb
class Testmodel < ActiveRecord::Base
end

app/models/user.rb
require 'bcrypt'
class User < ActiveRecord::Base
	def self.authenticate (username, password)
		admin = User.take
		username = admin.username && BCrypt::Password.new(admin.hashed_password).is_password?(password)
	end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_action :authorize
	
	def index
	end

	private
		def authorize
			unless session[:logged_in]
				redirect_to root_path
			end
		end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :authorize, except: [:index, :show]

	def new
		@authors = []
		buffer = Author.all
		buffer.each do |author|
			@authors.push([author.name, "#{author.id}"])
		end
	end

	def create
		@article = Article.new(article_params)
		if @article.save
		  redirect_to @article
		else
		  render 'new'
		end
	end

	def index
	  #Process offset, determine range of articles to pull
	  @offset = nil
	  @prev = nil
	  @next = nil
	  stop = Article.last.id
	  if params[:offset]
	  	#Nav
	  	@offset = Integer(params[:offset])
	  	@offset = 0 if @offset < 0
	  	@prev = @offset - 1 if @offset > 0
	  	@next = @offset + 1

	  	#Pull range
	  	stop = stop - (@offset * 15)
	  end	  
	  start = stop - 15
	  @next = nil if start < 1

	  #Pull articles and associate with authors
	  @authors = []
	  @articles = Article.where(id: start..stop)
	  @articles.each do |article|
	  	@authors.push Author.find_by(id: article.author_id)
	  end
	end

	def show
  		@article = Article.find(params[:id])
  		@author = Author.find_by(id: @article.author_id)
	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])
		if @article
			@article.update(article_params)
		end
	end

	private
	  def article_params
	    params.require(:article).permit(:title, :html, :title_image, :author_id)
	  end
	  def authorize
		  unless session[:logged_in]
			redirect_to root_path
		  end
	  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

    #Get latest stories, display them in the newblocks
  	@articles = Article.last(8)
    @articles.reverse!

    @authors = []
    @articles.each do |article|
      @authors.push Author.find_by(id: article.author_id)
    end

    @events = []
    curr_date = Date.today
    date_buffer = Date.new(curr_date.year, curr_date.month, curr_date.day)
    day = EventDay.find_by(date: date_buffer)

    (0...6).each do
      if !day.nil?
        day_buffer = Event.where(day_id: day.id)

        day_buffer.each do |event|
          buffer = {}
          buffer[:title] = event.title
          buffer[:time] = event.time
          buffer[:icon] = event.icon
          buffer[:day] = day.date
          @events.push buffer
        end
      end

      date_buffer = date_buffer+1
      day = EventDay.find_by(date: date_buffer);
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/comic_helper.rb
module ComicHelper
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/helpers/event_days_helper.rb
module EventDaysHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/podcast_helper.rb
module PodcastHelper
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :html %>
  </p>

  

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Destroy', @article, method: :delete, data: { confirm: 'Are you sure?' } %> | 
<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<% if session[:logged_in] %>
  <div class="newArticleBlock"><%= link_to( "New Article", new_article_path) %></div>
<% end %>
<div class="articleScroll">
  <h1 class="articleListHeader">Articles</h1>
  <% @articles.each_with_index do |article, index| %>
    <div class="articleItem">
      <div class="articleHeader">
          <div class="authorBlock">
            <%= image_tag("#{@authors[index].image}", class: 'authorImage') %><br>
            <div class="authorName"><%= @authors[index].name %></div>
          </div>
          <div class="titleBlock">
            <div class="articleTitle"><%= article.title %></div>&nbsp;-&nbsp;<div class="articleDate"><%= article.created_at.strftime("%e/%m/%y") %></div>
          </div>
          <div class="articleBtnWrapper">
            <%= link_to(image_tag('whiteforward.png', class: "articleBtn"), article) %>
            <% if session[:logged_in] %>
              <%= link_to(image_tag("whiteedit.png", class: "suedit2"), edit_article_path(article)) %>
            <% end %>  
          </div>           
      </div><br>  
    </div>
  <% end %>
</div>
<div class="pageBar">
  <% if @prev %>
    <%= link_to( image_tag('back.png', class: 'backArrow'), "/articles?offset=#{@prev}") %>
  <% end %>
  <% if @next %>
    <%= link_to( image_tag('next.png', class: 'nextArrow'), "/articles?offset=#{@next}") %>
  <% end %>
</div>

app/views/articles/manage.html.erb
<h1>Listing Articles</h1>
<%= link_to 'New Article', new_article_path %> | <%= link_to 'Back To Admin Panel', admin_path %><br><br>
<div class="divider"></div>
<% @articles.each do |article| %>
  <div class="itemListing">
    <div class="identifier">
      <%= article.title %> by <%= Author.find_by(article.author_id).name %>
    </div>
    <div class="actionBlock">
      <%= link_to 'Show', article %>&nbsp;|&nbsp;
      <%= link_to 'Edit', edit_article_path(article) %>&nbsp;|&nbsp;
      <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
    <div style="clear:both;"></div>
  </div><br> 
<% end %>

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= form_for :article, url: articles_path do |f| %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :author%>
    <%= f.select(:author_id, Author.all.collect {|author| [author.name, author.id]}, :prompt => 'Select') %>
  </p>

  <p>
    <%= f.label :image_url, "Title Image Url" %><br>
    <%= f.text_field :title_image %>
  </p>

  Image: &lt;img src="puturlhere"&gt; | Paragraph &lt;p&gt;putstuffhere&lt;/p&gt;

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :html %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<div class="articleContainer">
	<div class="articleInfoBlock">
		<div class="barBlock">
			<div class="titleBar"><%= @article.title %></div><br>
			<div class="dateBar"><%= @article.created_at.strftime("%B %d, %Y") %></div>
		</div>
		<div class="bigAuthorBlock">
			<%= image_tag(@author.image, class: "bigAuthorImage") %> <br>
			<div class="bigAuthorName"><%= @author.name %></div>
		</div>
		<div class="clear"></div>
	</div><br>
	<div class="articleText">
		<%= @article.html.html_safe%>
	</div>
</div>