config/routes.rb
Rails.application.routes.draw do
  resources :articles
  resources :authors
  resources :events
  resources :event_days
  resources :authors 

  get 'home/index'

  get 'calendar' => 'calendar#index'

  get 'login' => 'session#index'
  post 'login' => 'session#login'
  get 'logout' => 'session#logout'

  get 'admin' => 'admin#index'
  
  root 'home#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/author.rb
class Author < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/event_day.rb
class EventDay < ActiveRecord::Base
end

app/models/testmodel.rb
class Testmodel < ActiveRecord::Base
end

app/models/user.rb
require 'bcrypt'
class User < ActiveRecord::Base
	def self.authenticate (username, password)
		admin = User.take
		username = admin.username && BCrypt::Password.new(admin.hashed_password).is_password?(password)
	end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_action :authorize
	
	def index
	end

	private
		def authorize
			unless session[:logged_in]
				redirect_to root_path
			end
		end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  before_action :authorize

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name, :image)
    end

    def authorize
      unless session[:logged_in]
      redirect_to root_path
      end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

    #Get latest stories, display them in the newblocks
  	@articles = Article.last(8)
    @articles.reverse!

    @authors = []
    @articles.each do |article|
      @authors.push Author.find_by(id: article.author_id)
    end

    @events = []
    curr_date = Date.today
    date_buffer = Date.new(curr_date.year, curr_date.month, curr_date.day)
    day = EventDay.find_by(date: date_buffer)

    (0...6).each do
      if !day.nil?
        day_buffer = Event.where(day_id: day.id)

        day_buffer.each do |event|
          buffer = {}
          buffer[:title] = event.title
          buffer[:time] = event.time
          buffer[:icon] = event.icon
          buffer[:day] = day.date
          @events.push buffer
        end
      end

      date_buffer = date_buffer+1
      day = EventDay.find_by(date: date_buffer);
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/comic_helper.rb
module ComicHelper
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/helpers/event_days_helper.rb
module EventDaysHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/podcast_helper.rb
module PodcastHelper
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :image_url %>
  <%= f.text_field :image %>
  <br>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<h1>Listing Authors</h1>
<%= link_to 'New Author', new_author_path %> | <%= link_to 'Back To Admin Panel', admin_path %><br><br>
<div class="divider"></div>
<% @authors.each do |author| %>
  <div class="itemListing">
    <div class="identifier">
      <%= author.name %>
    </div>
    <div class="actionBlock">
      <%= link_to 'Show', author %>&nbsp;|&nbsp;
      <%= link_to 'Edit', edit_author_path(author) %>&nbsp;|&nbsp;
      <%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
    <div style="clear:both;"></div>
  </div><br> 
<% end %>

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>